%% inputBearingHertz
% Input parameters about bearing considering Hertzian contact
%% Synatx
% Parameter = inputBearingHertz(InitialParameter)
%% Description 
% InitialParameter: is a struct generated by inputEssentialParameter()
%
% All parameters about bearing with Hertzian contact should be typed into
% this .m file.
%
% All vectors in this .m file should be in column
% 
% The contact stiffness could be calculated by main_contactStiffness.mlx


function Parameter = inputBearingHertz(InitialParameter)
% typing the parameters about bearing considering the Hertz contact between
% rollers and races
BearingH.amount          = 3;
BearingH.inShaftNo       = [1; 1; 2];
BearingH.dofOfEachNodes  = [2; 2; 2]; % if mass=0, dof must be 0 
BearingH.positionOnShaftDistance = 1e-3 * [176.5; 718.5; 343.5];
BearingH.stiffnessSupport       = [1e8; 1e8; 1e8]; % N*m
BearingH.dampingSupport         = [300; 300; 300]; % N*s/m
BearingH.massPedestal           = [3; 3; 2.5]; % kg
BearingH.stiffnessRoller = [2.5e7; 2.5e7; 2.5e7]; % N*m
BearingH.dampingRoller = [150; 150; 150]; % N*s/m
BearingH.massOuterRace = [0.11; 0.11; 0.78]; % kg
BearingH.rollerNum = [8; 8; 10];
BearingH.radiusInnerRace = [28.8e-3; 28.8e-3; 75.5e-3]; % m
BearingH.radiusOuterRace = [47e-3; 47e-3; 110e-3]; % m
BearingH.clearance = [10e-6; 10e-6; 14e-6]; % m
BearingH.contactStiffness = [1.08e10; 1.08e10; 1.49e10]; % N*m^-3/2
BearingH.coefficient = [3/2; 3/2; 3/2]; % =3/2 in a ball bearing; = 10/9 in a roller bearing

checkInputData(BearingH)

% Outpt initialParameter
Parameter = InitialParameter;
Parameter.BearingH = BearingH; 
end